{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "OS DISK IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=~\"sd.\"}[$__rate_interval])\r\n",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Wait classes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(oracledb_system_wait_class_time_waited_sec_total[15s])",
     "legendFormat": "{{wait_class}}"
    }
   ]
  },
  {
   "title": "Host CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (mode, instance) (rate(node_cpu_seconds_total[$__rate_interval]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "AAS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(oracledb_sys_model_stm_value_sec_total{stat_name=\"DB time\", job=\"cdb19\"}[10s])",
     "legendFormat": "Avg Active Session"
    },
    {
     "expr": "rate(oracledb_sys_model_stm_value_sec_total{stat_name=\"DB CPU\", job=\"cdb19\"}[10s])",
     "legendFormat": "{{stat_name}}"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=~\"system|user\"}[15s]))",
     "legendFormat": "Host CPU (u|s)"
    }
   ]
  },
  {
   "title": "Number of active forground sessions",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_sessions_value{job=\"cdb19\", status='ACTIVE', type=\"USER\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(oracledb_order_count_order_total[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "quantile_over_time(.95, oracledb_order_gauge_order_no[60m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}