{
 "title": "Database",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "AAS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(oracledb_sys_model_stm_value_sec_total{stat_name=\"DB time\", job=\"cdb19\"}[$__rate_interval])",
     "legendFormat": "Avg Active Session"
    },
    {
     "expr": "rate(oracledb_sys_model_stm_value_sec_total{stat_name=\"DB CPU\", job=\"cdb19\"}[$__rate_interval])",
     "legendFormat": "{{stat_name}}"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=~\"system|user\"}[$__rate_interval]))",
     "legendFormat": "Host CPU (u|s)"
    }
   ]
  },
  {
   "title": "Wait classes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(oracledb_system_wait_class_time_waited_sec_total[$__rate_interval])",
     "legendFormat": "{{wait_class}}"
    },
    {
     "expr": "rate(oracledb_sys_model_stm_value_sec_total{stat_name=\"DB CPU\"}[$__rate_interval])",
     "legendFormat": "ON CPU"
    }
   ]
  },
  {
   "title": "bez pivot to wtedy sie skleja",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sort_desc(oracledb_ash_cnt_count{sql_id!=\"\"}/oracledb_ash_totalsum*100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": {
    "defaults": {
     "unit": "\"op/s\""
    }
   },
   "targets": [
    {
     "expr": "sum(rate(oracledb_system_stats_value_total{name=~\"consistent gets|db block gets\"}[$__rate_interval]))\r\n",
     "legendFormat": "\"logical reads\""
    },
    {
     "expr": "rate(oracledb_system_stats_value_total{name=~\"physical reads\"}[$__rate_interval])",
     "legendFormat": "\"physical reads\""
    }
   ]
  },
  {
   "title": "Redo Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(oracledb_system_stats_value_total{name=~\".*redo.*\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Undo Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(oracledb_system_stats_value_total{name=~\".*undo.*\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}