{
 "title": "DB events",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "wait_event",
    "query": {
     "query": "label_values(oracledb_event_hist_data_count,event)"
    }
   },
   { "name": "wait_class" }
  ]
 },
 "panels": [
  {
   "title": "Wait classes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(oracledb_system_wait_class_time_waited_sec_total[$__rate_interval])",
     "legendFormat": "{{wait_class}}"
    }
   ]
  },
  {
   "title": "Event time / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(oracledb_system_wait_event_time_waited_sec_total{wait_class=\"$wait_class\"}[$__rate_interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Wait_even_histogram",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(oracledb_event_hist_data_bucket{event='$wait_event'}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total waits / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(oracledb_system_wait_event_total_waits_total{wait_class=\"$wait_class\"}[$__rate_interval])",
     "legendFormat": "{{event}}"
    }
   ]
  }
 ]
}