{
 "title": "Sizing",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "ASM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MAX ASM DATA",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_asm_diskgroup_total{name=\"DATA\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oracledb_asm_diskgroup_total{name=\"DATA\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USED ASM DATA",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_asm_diskgroup_total{name=\"DATA\"}*0.8",
     "legendFormat": "Total"
    },
    {
     "expr": "oracledb_asm_diskgroup_total{name=\"DATA\"}-oracledb_asm_diskgroup_free{name=\"DATA\"}",
     "legendFormat": "USED"
    },
    {
     "expr": "oracledb_asm_diskgroup_total{name=\"DATA\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Tablespaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Used space",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_tablespace_bytes{job=\"pdb1\"}",
     "legendFormat": "{{tablespace}}"
    }
   ]
  },
  {
   "title": "% of free space of current allocation",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_tablespace_used_percent{job=\"pdb1\"}",
     "legendFormat": "{{tablespace}}"
    }
   ]
  },
  {
   "title": "Max tablespace size",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_tablespace_max_bytes{job=\"pdb1\"}",
     "legendFormat": "{{tablespace}}"
    }
   ]
  }
 ]
}