[[metric]]
context = "order_gauge"
request = '''
select count(*) as order_no from orders where order_Date > (CURRENT_TIMESTAMP - interval '1' minute)
'''
labels = []
metricsdesc = { order_no="gauge metric number of orders per 60 sec" }
metricstype = { order_total = "gauge" }
ignorezeroresult = true
