apiVersion: v1
kind: Service
metadata:
  name: metrics-svc-pdb1
  namespace: grafana
  labels:
    app: metrics-exporter-pdb1
spec:
  type: ClusterIP
  ports:
    - port: 9161
      name: metrics
      targetPort: 9161
  selector:
    app: metrics-exporter-pdb1