apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-exporter-cdb19
  namespace: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-exporter-cdb19
  template:
    metadata:
      labels:
        app: metrics-exporter-cdb19
    spec:
      containers:
      - name: metrics-exporter
        image: container-registry.oracle.com/database/observability-exporter:1.3.1
        imagePullPolicy: Always
        env:
          - name: CUSTOM_METRICS
            value: /oracle/observability/custom-metrics.toml
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: username
                optional: false
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
                optional: false
          - name: DB_CONNECT_STRING
            valueFrom:
              configMapKeyRef:
                name: cdb-db-config
                key: connectionstring
        volumeMounts:
          - name: config-volume
            mountPath: /oracle/observability
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"  
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: custom-db-metrics
