apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-exporter-pdb1
  namespace: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-exporter-pdb1
  template:
    metadata:
      labels:
        app: metrics-exporter-pdb1
    spec:
      containers:
      - name: metrics-exporter
        image: container-registry.oracle.com/database/observability-exporter:1.3.1
        imagePullPolicy: Always
        args:
        # disable default metrics as from PDB I want to see only my SQL
          - "--default.metrics=/oracle/observability/custom-metrics-pdb.toml"
          - "--log.level=debug"
          - "--query.timeout=30"
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: pdb-secret
                key: username
                optional: false
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pdb-secret
                key: password
                optional: false
          - name: DB_CONNECT_STRING
            valueFrom:
              configMapKeyRef:
                name: pdb-db-config
                key: connectionstring
        volumeMounts:
          - name: config-volume
            mountPath: /oracle/observability
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"  
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: custom-pdb-metrics 
